version: 2
jobs:
  build:
    docker:
      - image: php:7.1-apache
    steps:
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng12-dev gzip bzip2 tar
      - run:
          name: Build php extensions
          command: docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - run:
          name: Install PHP extensions
          command: docker-php-ext-install -j$(nproc) pdo pdo_mysql iconv mcrypt gd
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
      - restore_cache:
            keys:
              - composer-v1-{{ checksum "composer.json" }}
              - composer-v1-
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
